services:
  hyper:
    image: timescale/timescaledb:latest-pg17
    container_name: supervisorio-test
    restart: always
    environment:
      POSTGRES_USER: hyper
      POSTGRES_PASSWORD: hyper
      POSTGRES_DB: metrics_test
    ports:
      - "5440:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hyper"]
      interval: 10s
      timeout: 5s
      retries: 5
