version: "3.9"

services:
  # ---------------------------
  # Banco de Dados TimescaleDB
  # ---------------------------
  db:
    image: timescale/timescaledb:latest-pg17
    container_name: supervisorio-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: supervisorio
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  # ---------------------------
  # Backend (Fastify / Node)
  # ---------------------------
  supervisorio-server:
    build:
      context: .
      dockerfile: Dockerfile          # teu Dockerfile do server
      target: supervisorio-server     # target do server no Dockerfile
    container_name: supervisorio-server
    environment:
      PORT: 3333
      API_URL: http://localhost:3333
      WEB_URL: http://localhost:3000

      # DB Connection
      HYPER_DATABASE_URL: postgres://postgres:password@db:5432/supervisorio

      # Auth
      JWT_SECRET: "d43a102e-dff8-4310-9f8e-8de8188840b5"
      PASSWORD: "$argon2id$v=19$m=65536,t=3,p=4$wSq5mPIYnkzaGwqR5PPlPA$hvuEkrCSf1XD4ybsw+/EpdxgufYBrwXPHesWxq0fhJA"

    ports:
      - "3333:3333"

    depends_on:
      db:
        condition: service_healthy


  # ---------------------------
  # Frontend (Vite + nginx)
  # ---------------------------
  supervisorio-web:
    build:
      context: .
      dockerfile: Dockerfile.web      # Dockerfile especial do web
    container_name: supervisorio-web
    ports:
      - "3000:80"
    depends_on:
      - supervisorio-server
