services:
  db:
    image: postgres:16
    container_name: supervisorio-postgr
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    command: >
      postgres
      -c max_connections=200
      -c shared_buffers=2GB
      -c effective_cache_size=6GB
      -c maintenance_work_mem=512MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=9892kB
      -c huge_pages=off
      -c min_wal_size=1GB
      -c max_wal_size=4GB
      -c max_worker_processes=12
      -c max_parallel_workers_per_gather=4
      -c max_parallel_workers=12
      -c max_parallel_maintenance_workers=4

  hyper:
    image: timescale/timescaledb:latest-pg17
    container_name: hyper_supervisorio-postgr
    restart: always
    environment:
      POSTGRES_USER: ${HYPER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${HYPER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${HYPER_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - ./.data/hyper_postgres:/var/lib/postgresql/data
